export const configConstants = {
  CONFIGS_REQUEST: "USERS_CONFIGS_REQUEST",
  CONFIGS_LOADING: "USERS_CONFIGS_LOADING",
  CONFIGS_FAILURE: "USERS_CONFIGS_FAILURE",
  CONFIGS_SUCCESS: "USERS_CONFIGS_SUCCESS",
  PROFILE_SETTINGS_REQUEST:'USER_PROFILE_SETTINGS_REQUEST',
  PROFILE_SETTINGS_SUBMIT:'USER_PROFILE_SETTINGS_SUBMIT'
};
